### ISSUE TITLE
2 Error's in README.md

### ISSUE THREAD

**Issue by my-digital-life** [dlakelan/routerperf#12]
While copy pasting your instruction on the read me page I noticed an error

wget --no-check-certificates https://raw.githubusercontent.com/dlakelan/routerperf/master/SimpleHFSCgamerscript.sh

Should be (notice the "s")
wget --no-check-certificate.....

Same as the next command
wget --no-check-certificates https://raw.githubusercontent.com/dlakelan/routerperf/master/dscptag.sh

**Comment by dlakelan** [comment]
Fixed, thanks!

**Comment by dlakelan** [comment]
committed change, closing issue
